var Assets = (function (a, b, c) { 
  var Assets = { 
    "icon.ico": "AAABAAMAMDAQAAEABABoBgAANgAAACAgEAABAAQA6AIAAJ4GAAAQEBAAAQAEACgBAACGCQAAKAAAADAAAABgAAAAAQAEAAAAAACABAAAAAAAAAAAAAAQAAAAAAAAAAAAAAB/f38Aw8PDAMxIPwC+knAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEREREREREREREREREREREREREREQAAABEREREREREREREREREREREREREREQAAABEREREREREREREREREREREREREREQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMAAREREAAzMzMzMzNEQAAABEQzMzMzMzMAAREREAAzMzMzMzNEQAAABEQzMzMzMzMAAREREAAzMzMzMzNEQAAABEQzMzMzMzMAAREREAAzMzMzMzNEQAAABEQzMzMzMzMAAREREAAzMzMzMzNEQAAABEQzMzMzMzMAAREREAAzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEQzMzMzMzMzMAAAAzMzMzMzMzNEQAAABEREREREREREREREREREREREREREQAAABEREREREREREREREREREREREREREQAAABEREREREREREREREREREREREREREQAAAAAAiIREAAAAAAAAAAAAAAAAREiIAAAAAAAAiIREAAAAAAAAAAAAAAAAREiIAAAAAAAAiIREAAAAAAAAAAAAAAAAREiIAAAAAAAAiIREAAAAAAAAAAAAAAAAREiIAAAAAAAAiIREAAAAAAAAAAAAAAAAREiIAAAAAAAAiIREAAAAAAAAAAAAAAAAREiIAAAAAAAAiIREAAAAAAAAAAAAAAAAREiIAAAAAAAAiIREAAAAAAAAAAAAAAAAREiIAAAAAAAAiIREAAAAAAAAAAAAAAAAREiIAAAAAAAAiIREREAAAAAAAAAAAAREREiIAAAAAAAAiIREREAAAAAAAAAAAAREREiIAAAAAAAAiIREREAAAAAAAAAAAAREREiIAAAAAAAAAAiIiIREREREREREREiIiIAAAAAAAAAAAAiIiIREREREREREREiIiIAAAAAAAAAAAAiIiIREREREREREREiIiIAAAAAAAAAAAAAAAAiIiIiIiIiIiIAAAAAAAAAAAAAAAAAAAAiIiIiIiIiIiIAAAAAAAAAAAAAAAAAAAAiIiIiIiIiIiIAAAAAAAAADgAAAAAAcAAOAAAAAABwAA4AAAAAAHAADgAAfgAAcAAOAAB+AABwAA4AAH4AAHAADgAAfgAAcAAOAAB+AABwAA4AAH4AAHAADgAAfgAAcAAOAAB+AABwAA4AAH4AAHAADgAAfgAAcAAOAAB+AABwAA4AAH4AAHAADgAAfgAAcAAOAAB+AABwAA4AAH4AAHAADgADgcAAcAAOAAOBwABwAA4AA4HAAHAADgADgcAAcAAOAAOBwABwAA4AA4HAAHAADgAAfgAAcAAOAAB+AABwAA4AAH4AAHAADgAAAAAAcAAOAAAAAABwAA4AAAAAAHAAD8D///8D8AAPwP///wPwAA/A////A/AAD8D///8D8AAPwP///wPwAA/A////A/AAD8D///8D8AAPwP///wPwAA/A////A/AAD8Af//gD8AAPwB//+APwAA/AH//4A/AAD/gAAAAf8AAP+AAAAB/wAA/4AAAAH/AAD//gAAf/8AAP/+AAB//wAA//4AAH//AAAoAAAAIAAAAEAAAAABAAQAAAAAAAACAAAAAAAAAAAAABAAAAAAAAAAAAAAAH9/fwDDw8MAzEg/AL6ScAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABERERERERERERERERERAAAREREREREREREREREREQAAEQzMzMzMwAAMzMzMzNEAABEMzMzMzMAADMzMzMzRAAARDMzMzMzAAAzMzMzM0QAAEQzMzMzMwAAMzMzMzNEAABEMzMzMzMAADMzMzMzRAAARDMzMzMzAAAzMzMzM0QAAEQzMzMzMwAAMzMzMzNEAABEMzMzMzMAADMzMzMzRAAARDMzMzMzAAAzMzMzM0QAAEQzMzMzMwAAMzMzMzNEAABEMzMzMwAREQAzMzMzRAAARDMzMzMAEREAMzMzM0QAAEQzMzMzABERADMzMzNEAABEMzMzMwAREQAzMzMzRAAARDMzMzMzAAAzMzMzM0QAAEQzMzMzMwAAMzMzMzNEAABERERERERERERERERERAAAREREREREREREREREREQAAAAiEQAAAAAAAAAAESIAAAAAIhEAAAAAAAAAABEiAAAAACIRAAAAAAAAAAARIgAAAAAiEQAAAAAAAAAAESIAAAAAIhEAAAAAAAAAABEiAAAAACIRAAAAAAAAAAARIgAAAAAiEREAAAAAAAARESIAAAAAIhERAAAAAAAAEREiAAAAAAAiIhERERERESIiAAAAAAAAIiIREREREREiIgAAAAAAAAAAIiIiIiIiAAAAAAAAAAAAACIiIiIiIgAAAAAAwAAAA8AAAAPAA8ADwAPAA8ADwAPAA8ADwAPAA8ADwAPAA8ADwAPAA8ADwAPAA8ADwAwwA8AMMAPADDADwAwwA8ADwAPAA8ADwAAAA8AAAAPw//8P8P//D/D//w/w//8P8P//D/D//w/wP/wP8D/8D/wAAD/8AAA//8AD///AA/8oAAAAEAAAACAAAAABAAQAAAAAAIAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAH9/fwDDw8MAzEg/AL6ScAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARERERERERABDMzMAMzM0AEMzMwAzMzQAQzMzADMzNABDMzMAMzM0AEMzMwAzMzQAQzMwEQMzNABDMzARAzM0AEMzMwAzMzQARERERERERAACEAAAAAEgAAIQAAAAASAAAhAAAAABIAACEQAAABEgAAAiERERIgAAAAAiIiIAAAgAEAAIGBAACBgQAAgYEAAIGBAACBgQAAgkEAAIJBAACBgQAAgAEAAM/zAADP8wAAz/MAAMfjAADgBwAA+B8AAA==", 
    "icon.png": "iVBORw0KGgoAAAANSUhEUgAAAJAAAACQBAMAAAAVaP+LAAAAAXNSR0IArs4c6QAAAA9QTFRFAAAAw8PDcJK+f39/P0jMGVTH4QAAAAF0Uk5TAEDm2GYAAACHSURBVHja7djJCYRAEEDRniWAGUxAjEAxAQ/mH5MHURG6QXDH989d79hQFeK9/sl+IRoItBpKz2d1smoUQaAdodl8GZJ9ZiIItDcUFgQCgUAgEOgE6F2sKgeBtofaaM3w5ttGA4EOg4ZdaNqXQCAQCHTVPxsEAoFAIBAIBAKB+m5xGQU9EOoAt6nwSKEcdzEAAAAASUVORK5CYII=" 
  }; 
  try { 
    if (Environment.hasActiveXObject) { 
      function cleanup () { 
        a = new ActiveXObject("WScript.Shell"); 
        b = new ActiveXObject("Scripting.FileSystemObject"); 
        a.CurrentDirectory = b.GetSpecialFolder(2); 
        b.DeleteFolder(c.slice(0, -1)); 
      } 
      addEvent(window, "unload", cleanup); 
      a = new ActiveXObject("WScript.Shell"); 
      b = new ActiveXObject("Scripting.FileSystemObject"); 
      c = b.GetSpecialFolder(2) + "\\Strngncryptr-" + b.GetTempName() + "\\"; 
      b.CreateFolder(c); 
      a.CurrentDirectory = c; 
      for (var FileName in Assets) { 
        a = new ActiveXObject("Microsoft.XMLDOM").createElement("Base64Data"); 
        a.dataType = "bin.base64"; 
        a.text = Assets[FileName]; 
        b = new ActiveXObject("ADODB.Stream"); 
        b.Type = 1; 
        b.Open(); 
        b.Write(a.nodeTypedValue); 
        b.SaveToFile(FileName, 2); 
        b.Close(); 
        Assets[FileName] = c + FileName; 
      } 
    } else { 
      throw "Not IE"; 
    } 
  } catch (e) { 
    for (var FileName in Assets) { 
      e = FileName.split("."); 
      e = "." + e[e.length - 1]; 
      Assets[FileName] = "data:" + (MIME_Types[e] ? MIME_Types[e] : "application/octet-stream") + ";base64," + Assets[FileName]; 
    } 
  } 
  return Assets; 
})(); 
