var MIME_Types = {
  '.html': 'text/html',
  '.htm': 'text/html',
  '.gif': 'image/gif',
  '.jpeg': 'image/jpeg',
  '.jpg': 'image/jpeg',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.wav': 'audio/wav',
  '.webp': 'image/webp',
  '.webv': 'video/webm',
  '.weba': 'audio/webm',
  '.webm': 'video/webm',
  '.oga': 'audio/ogg',
  '.opus': 'audio/ogg; codecs=opus',
  '.ogv': 'video/ogg',
  '.ogg': 'application/ogg',
  '.m4v': 'video/mp4',
  '.m4a': 'audio/mp4',
  '.mp4': 'video/mp4',
  '.mp3': 'audio/mpeg',
  '.aac': 'audio/aac',
  '.flac': 'audio/flac',
  '.flv': 'video/x-flv',
  '.m3u8': 'audio/mpegurl',
  '.ts': 'video/MP2T',
  '.3gp': 'video/3gpp',
  '.mov': 'video/quicktime',
  '.avi': 'video/x-msvideo',
  '.wmv': 'video/x-ms-wmv',
  '.css': 'text/css',
  '.js': 'application/javascript',
  '.txt': 'text/plain',
  '.wml': 'text/vnd.wap.wml'
};